### ISSUE TITLE
Improve UX for adding ingredients to a recipe

### ISSUE THREAD

**Issue by switzerb** [switzerb/CookBook#10]
Right now there is an add button at the end of each add ingredient row that needs to be hit to add a new ingredient. It's confusing and needs to be changed.

**Comment by barneyb** [comment]
the "environment variables" editor in the beanstalk config might provide some inspiration.

**Comment by switzerb** [comment]
This is being replaced with "reconciliation" for ingredient matching and has been removed from the add process, so closing.
