### ISSUE TITLE
Migrate Task List --> Planner

### ISSUE THREAD

**Issue by switzerb** [switzerb/CookBook#103]
Steps to get the task list squarely into the planner territory, in order of operations:

- Adapt Task model from storing strings to dealing gracefully with Item (ingredientref)
- Add status concept to Item (ingredient ref) with completed/acquired
- Replacing ant with material design
- Drop in el edit into the task list
- Make the shopping list aggregation possible
- untangle "edit recipe" vs "edit tasks". "add to planner", copies of recipes to planner, etc
- side panel, desktop/mobile bullshit to address.
- drag and drop

**Comment by barneyb** [comment]
Aside from the "untangle" and "side panel" items, of this is done. Both of those warrant their own issues, and quite possible several each. But now we're in a position to actually have that conversation, so I'm gonna close this as "too nebulous; mostly done."
