### ISSUE TITLE
Preview ShoppingList

### ISSUE THREAD

**Issue by barneyb** [switzerb/CookBook#71]
need a way to preview the shopping list, before saving it and converting it to tasks. Maybe a sidebar thing like amazon's shopping cart?

**Comment by barneyb** [comment]
This was actually the whole issue with Saturday: there was no way to build up the shopping list during planning, it was purely an output at the end. It needs to be integrated into the planning experience, so you can add (and remove!) stuff on the fly, as you’re planning.

**Comment by barneyb** [comment]
The shopping list is simply an alternate view of a plan, where there are no "container" items, only PantryItems, and their quantities are aggregated. If it ships to a task list or not is sort of immaterial, the important part is that "shopping list" is _NOT_ a transformation from the plan into a task list, but rather an _alternate view_ of the plan itself (which may end up being serialized to a task list).

**Comment by switzerb** [comment]
We've decided this is a specific view of the planner and therefore has been obsoleted by some UX planning. Closing this as "won't do"
