### ISSUE TITLE
Kitchen View

### ISSUE THREAD

**Issue by barneyb** [switzerb/CookBook#75]
It'd be _great_ to have a "i'm in the kitchen cooking" view of a recipe (or menu?), separate from the normal detail view. In particular:

1. allow checking off ingredients (cross them out, and maybe reduce opacity?)
1. allow checking off directions (if they're in a multi-item format of some sort)
1. less "manage stuff" UI bits
1. ability to easily add ingredient deltas and/or notes while cooking

**Comment by switzerb** [comment]
Note that this would display the ephemeral version of the recipe, not the canonical one. This needs to be the specific version from the planner.

**Comment by barneyb** [comment]
I'm gonna close this as complete. Cooking from the plan is available, with a dedicated low-noise view. It's unclear if/how the other bells and whistles ought to work, so left open-ended for the future (or not).
