### ISSUE TITLE
Recipe Template (recipe) vs Recipe Instance (dish)

### ISSUE THREAD

**Issue by barneyb** [switzerb/CookBook#76]
Bad names. But some sort of expression of "i'm preparing a dish from a recipe" distinction, where there's a base recipe that you're using, but you want to also express things about the dish you're currently making (presumably from the recipe in question).  At it's simplest, add some notes to this use of the recipe. More complex would be munging ingredients, either changing quantities or omitting/adding them.

This gets into recipe versioning as well, of course. But this isn't about a new recipe version, it's more like treating a recipe as a Java Class, and a dish as an instance of that Class. Every time you prepare a recipe, the resulting dish is ... distinct from the recipe. And different from other dishes prepared from the same recipe. That's really important. Like _REALLY_ important.

**Comment by barneyb** [comment]
This could be modeled as "recipe has a series of dishes based on it" where each dish has it's own mods to the ingredients, notes, comments, who knows. Collecting that data is useful, so it can be reviewed later to drive changes to the recipe.

**Comment by switzerb** [comment]
Just documenting the decisions we made over the weekend here. The "Planner" is ephemeral and contains copies of the recipes/meals/grocery items that can be manipulated at will. Although it would then be (theoretically at this point) possible to save off a persistent copy of these things back to the template, in the planner they are time-bound and singular instances. The planner contains instances, the library contains templates.

And, as a corollary decision, "Meals" as a conceptual grouping are "recipe-like" not "planner-like" meaning they are persistent references, not instances. If you change the underlying recipe that is referenced by a meal, it will change the meal. If you add a meal to a planner and then change the underlying recipe, it will not change the meal (or the recipe) in the library.

Clear as mud? Good!

**Comment by barneyb** [comment]
This isn't _quite_ done, but it's pretty close. The richness of a recipe sent to the plan is still too low, and there's no way to later say "yeah, that was awesome, please push the changes to the planned recipe back to the library." But we're a long way along.

**Comment by barneyb** [comment]
With the ability to now cook from the plan (instead of the original recipe in the library), I'm calling this one done. Hardly perfect, but the main idea is there, and future enhancement can come as new issues.
