### ISSUE TITLE
Instrument Foodinger with New Relic Pro

### ISSUE THREAD

**Issue by switzerb** [switzerb/CookBook#77]
- it'd _definitely_ be useful to get production stack traces (both client- and server-side!) into NR
- on the performance side, i'd be interested in how much time is spent w/ ajax in flight, broken down by "background" or "user is waiting"
- but gonna also need some sort of "amount of interaction" number for the denominator.
- and in the _very_ specific, i'd be interesting to measure how much waste my task list background refresh thing causes, e.g., how often does it refresh for no-benefit in an absolute sense, _and_ percentage of total refreshes

**Comment by barneyb** [comment]
* query count, frequency, and speed would be nice too. the current JPA config is _massively_ non-performant. measuring exactly where/how would be useful

**Comment by barneyb** [comment]
impossible!
