### ISSUE TITLE
Fix add redirect weirdness

### ISSUE THREAD

**Issue by switzerb** [switzerb/CookBook#88]
Potentially, this will require shipping source maps to production, which is not super awesome but might be incredibly useful in the short term.

**Comment by barneyb** [comment]
Shipping source maps seems pretty desireable. It'll also richen the utility
of newrelic's JS stuff. We already publicly share the source code, so there
isn't an IP concern.

**Comment by barneyb** [comment]
A hA HAHA HA! NewRelic refuses to use published sourcemaps. So not that one. But sourcemaps _are_ shipped to production, so  that part's good to go.

**Comment by barneyb** [comment]
I'm not sure what the description and comments are referring to, but the weirdness around the draft add/edit for is spiffier now.
